
from pathlib import Path

import numpy as np
import pandas as pd

from src.simulation.network import build_microgrid, run_simulation
from src.estimation.measurement_model import (
    build_dc_measurement_model,
    check_observability,
)


def generate_dc_measurements(seed=42, noise_std_mw=0.01):
    """
    Generate reproducible synthetic DC active-power measurements.

    Args:
        seed: Random seed for reproducibility.
        noise_std_mw: Standard deviation of measurement noise in MW.

    Returns:
        measurements: DataFrame containing line measurements.
        reference_states: DataFrame containing reference bus angles.
        H: DC measurement matrix.
    """
    if noise_std_mw < 0:
        raise ValueError("noise_std_mw cannot be negative.")

    # Build and solve the existing microgrid.
    net = run_simulation(build_microgrid())

    H, measurement_info, state_bus_ids = (
        build_dc_measurement_model(net, reference_bus=0)
    )

    # Use the AC power-flow angles as reference states.
    # Convert degrees to radians and fix bus 0 as the reference.
    all_angles_rad = np.deg2rad(
        net.res_bus["va_degree"].to_numpy()
    )

    reference_angle = all_angles_rad[
        list(net.bus.index).index(0)
    ]

    all_angles_rad = all_angles_rad - reference_angle

    # State vector contains all non-reference bus angles.
    theta_true = np.array([
        all_angles_rad[list(net.bus.index).index(bus_id)]
        for bus_id in state_bus_ids
    ])

    # Ideal measurements generated by the linear DC model.
    true_flows_mw = H @ theta_true

    rng = np.random.default_rng(seed)
    noise = rng.normal(
        loc=0.0,
        scale=noise_std_mw,
        size=len(true_flows_mw),
    )

    measured_flows_mw = true_flows_mw + noise

    measurements = measurement_info.copy()
    measurements["true_flow_mw"] = true_flows_mw
    measurements["noise_mw"] = noise
    measurements["measured_flow_mw"] = measured_flows_mw

    reference_states = pd.DataFrame({
        "bus_id": state_bus_ids,
        "reference_angle_rad": theta_true,
        "reference_angle_degree": np.rad2deg(theta_true),
    })

    return measurements, reference_states, H


if __name__ == "__main__":
    output_dir = Path("data/raw")
    output_dir.mkdir(parents=True, exist_ok=True)

    measurements, states, H = generate_dc_measurements(
        seed=42,
        noise_std_mw=0.01,
    )

    measurement_path = output_dir / "dc_measurements.csv"
    state_path = output_dir / "dc_reference_states.csv"

    measurements.to_csv(measurement_path, index=False)
    states.to_csv(state_path, index=False)

    observability = check_observability(H)

    print("\n=== DC MEASUREMENT MATRIX ===")
    print(H)

    print("\n=== OBSERVABILITY CHECK ===")
    print(observability)

    print("\n=== ACTIVE-POWER MEASUREMENTS ===")
    print(measurements.to_string(index=False))

    print("\n=== REFERENCE STATE ANGLES ===")
    print(states.to_string(index=False))

    print(f"\nSaved measurements: {measurement_path}")
    print(f"Saved reference states: {state_path}")
